name: 自动爬取校园通知 # 工作流的名字

on:
  push:
    branches: [ "main" ] # 当向main分支推送代码时触发
  schedule:
    - cron: '0 6 * * *' # 每天UTC时间6:00（北京时间14:00）定时触发:cite[6]
  workflow_dispatch: # 允许在GitHub网页上手动触发运行

jobs:
  crawl:
    runs-on: ubuntu-latest # 使用最新的Ubuntu系统作为运行环境

    steps:
    # 步骤1：获取仓库代码
    - name: 检出代码
      uses: actions/checkout@v4

    # 步骤2：设置Python环境
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.5' # 指定你项目使用的Python版本

    # 步骤3：安装依赖
    - name: 安装Python依赖
      run: |
        pip install -r requirements.txt

    # 步骤4：运行爬虫脚本
    - name: 执行爬虫
      run: python scripts/spider.py # 执行爬虫脚本

    # 步骤5：提交爬取的数据（可选）
    - name: 提交数据变更
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/notices.json # 爬虫生成的数据文件
        git commit -m "Auto: update data" || echo "没有变更可提交"
        git push